
CREATE USER C##BOT_RPA IDENTIFIED BY botrpa;
GRANT CONNECT TO C##BOT_RPA;
ALTER USER C##BOT_RPA QUOTA UNLIMITED ON USERS;

-- Create Table Process Log
CREATE TABLE "C##BOT_RPA"."PROCESS_LOG" 
(
    "LOG_SEQ" NUMBER GENERATED ALWAYS AS IDENTITY NOT NULL, 
    "PROCESS_NAME" VARCHAR2(100) NOT NULL, 
    "DOC_NAME" VARCHAR2(150) NULL, 
    "ISSUE_DATE" CHAR(8) NULL, 
    "AGENT_CODE" CHAR(4) NULL, 
    "VERSION" VARCHAR2(5) NULL, 
    "LOG_STATUS" CHAR(1) NOT NULL CHECK ("LOG_STATUS" IN ('0', '1', '2', '3','4','5','6')), 
    "LOG_DESC" VARCHAR2(255), 
    "CREATED_BY" VARCHAR2(100) NOT NULL, 
    "LOG_TIMESTAMP" TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

-- Create Index for DOC_NAME
CREATE INDEX IDX_PROCESS_LOG_DOC_NAME 
ON C##BOT_RPA.PROCESS_LOG (DOC_NAME);

CREATE INDEX IDX_PROCESS_LOG_LOG_TIMESTAMP 
ON C##BOT_RPA.PROCESS_LOG (LOG_TIMESTAMP);

-- Grant privileges
GRANT SELECT, INSERT, UPDATE, DELETE ON C##BOT_RPA.PROCESS_LOG TO C##BOT_RPA;
GRANT DBA TO C##BOT_RPA;

-- Set Auto Commit Off
SET AUTOCOMMIT OFF;


